

# ---- DB (מגיע ממשתני סביבה ב-Render) ----
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.data-source-properties.sslmode=require

# ---- JPA ----
spring.jpa.hibernate.ddl-auto=update

# OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ezdrive.israel@gmail.com
spring.mail.password=qpqy cpey fgum llkb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS}

google.client.id=${GOOGLE_CLIENT_ID}

# ---- Render port binding ----
server.port=${PORT:8080}

# ---- Session cookie & proxy 
server.forward-headers-strategy=framework
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true

app.cors.allowed-origins=https://ezdrive-client.onrender.com

app.otp.enabled=true



