spring.datasource.url=jdbc:postgresql://localhost:5432/EZDrive
spring.datasource.username=postgres
spring.datasource.password=shiragiladi
spring.jpa.hibernate.ddl-auto=update

# ---- Google OAuth (local) ----
google.client.id=250713696752-4k026jggdvnitarn3efqudooqignqc68.apps.googleusercontent.com

app.otp.enabled=false
