spring.datasource.url=jdbc:postgresql://localhost:5432/EZDrive
spring.datasource.username=postgres
spring.datasource.password=shiragiladi
spring.jpa.hibernate.ddl-auto=update

# ---- Google OAuth (local) ----
google.client.id=250713696752-4k026jggdvnitarn3efqudooqignqc68.apps.googleusercontent.com

# OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ezdrive.israel@gmail.com
spring.mail.password=qpqy cpey fgum llkb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.otp.enabled=true

app.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000
